language: android

android:
   components:
   #- tools
   #- platform-tools
   - android-25
   - build-tools-25.0.0
   #- extra

jdk: oraclejdk8

notifications:
  email: false

before_install:
   - touch local.properties
   - source gradle.properties
   - .travis/env.sh
   - openssl aes-256-cbc -K $encrypted_fcd823279b44_key -iv $encrypted_fcd823279b44_iv -in release.jks.enc -out release.jks -d

script:
  - ./gradlew clean assembleDebug
  - cp app/build/outputs/apk/Kindle-v$VERSION_NAME-debug.apk $HOME
  - ./gradlew clean assembleRelease
  - cp app/build/outputs/apk/Kindle-v$VERSION_NAME-release.apk $HOME
  - md5sum "$HOME/Kindle-v$VERSION_NAME-debug.apk"
  - md5sum "$HOME/Kindle-v$VERSION_NAME-release.apk"
  - sha1sum "$HOME/Kindle-v$VERSION_NAME-debug.apk"
  - sha1sum "$HOME/Kindle-v$VERSION_NAME-release.apk"

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "$HOME/Kindle-v$VERSION_NAME-debug.apk"
    - "$HOME/Kindle-v$VERSION_NAME-release.apk"
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    # GITHUB_TOKEN
    - secure: "bIweBT4zDjWBwdh7j450csuzAKUfzFR4WbzpVBTI8YQ3pKPO5ic9AkyXgC1iK6rDs65flPF3HhzdFpMFFg3mXWKaKq8D/m0BAw2UwIVmsMgG18zP6D/75ExtGJOwUtfiZFvuORB74bfK+yHd+jklQ148btEPZpem+A/FD70iD+O/lCw6EPy7rN98+cIOb/38hhxqHmyJV6sC9njdCOfj2pbCxd/kJdPGLOYeeNw3SbAr/6t/p9SCJZt+9exEdjuRz2kkr4NwHdbbAmcaNiqUwGLFT/duQL7HJbzpn0Rz8eX3GJG3ESu4O7ma29lLoyh8/vySipaOiboPfdcwy3uiN/Ki4GHoPvoempZe3/wg4fNubJ0ZBNjSyDZ884TydG7J84dGqZUPvGfGl0zY9BIKtlVGIZa4qtmO4K9IV7xcufA3o0Sa0rKZ5Yyd6YanSdtxH5BvK93ak2dRc1cRYGKzuf4ypdHvrHIb7ftPUqmDL63TgVr+zltkKrUx8cu4fxXZc70diHkOjz+0yH8KQB39CvPmJwbhVM74e+1zTius7PfjTqKbJdUz8R5EHBAKswLjGdZ+nulk4zWRoO0RRiUzYitRKFw5QbuyKmt2Pdh00OX2hqj5LitXGPNP+Gq4BnlTxyzS3nF9eiobIp8W7bkFmsIjBXLna6jN+c2CGC9oLnM="
    # KEYSTORE_PASSWORD
    - secure: "ENEm2RbN0BvqKE7O69Zu4RKLZL+fTvifYBfyaVnNFJrwGjcMMJYTZ+4JmBRN2HNUhz6p3o8KgaQ3NlzRQIJTe5/pmbRPrfV5gN5AlB/hPKx17KVUJP85GEmya5Cqbg0eUP2l/QaURpH9VTugkALXNpUPU1GMH1BxJ76uAEEFmsRBleT8R8Miee+1xI59eCxGKWOrX7zuGu6z1wV5figNoDB2aJ7yDOLhFztAo/njX4oci8TanHNu6k7y5yBCg1shFKTuH94tLaz6eRQnWQfmXAQadskcoxOCvk4BshMW6KLXzOVYMKA73kMt6gCwBSfGaKsphGzFs9nwiDo1NmL9nGO0XyHFhPRytvFbHwWIkchK+5eF20ZtREcRww42bjYPBffDan6Cq2oORKhB7sBi5bzhXomDPcaaFPNkIlEjA7TUThVYP6fc0YiaJVikkTSlaKtP6+NlhjW/6gNiJc3BUDB3BDPlbfY05+St1rAInNBZ56oiMyptvlYyVbvK3EnymwpL/FbGqOKBXKcysgplQ9mstQc8p6ndMucSDdhKdgUyxOLBGuyuZDGQc3CeMN1d5eJEW8bsx//gpw18+HRM3ykK2SBLDH/rJpDvvRF07u9vfblLe9GZFUtmX67Ti8Jjax4wipAWIbEl/VnuL9m8d6LqC1baUMt1FbIIebZur6U="
    # ALIAS_PASSWORD
    - secure: "n+txXzczrrIDPt2SF/w4ojBYzDSLqS4MlmcDg9ir74ZFxQpuRvyQWTkTCKJZ/A9OVdfXZS5Xh7zt1XYKDPitY6LMxCNaRXjCyl+7NaSnSSSFLDCAjE8nzIhseAAGkQCfoq0nPxnN98tO12q9K4Ub8+hF4yavVJLdMbGyqG++T3SpJvdIRQ8lKDj3r0c7JcV4ps6jnIEqFhnPcY4UKc1am+dlBgFyOlw4gN2FnFUqrXrkis2KMa5VqOBo1arWAl71acui60XbAUb9xiZ+H+yw5rGm8Y0XoPtJCH2Nkb+Bv3J2XMyvYiJX51+1Yt8GlLDdI1MbQOZUti3BLgkWMSLn4cMlNtj7jsNZwRREBZQtqEYZXt1n9E6fuuLvZfL8UqLDxjd2PX77SCrwqNxb6ck6Pe9hR6E7pwJgdrhoGfFo3YgcWMXrE7DlMZWtLgfC4/w7VizMaEFdvmReoXpHDIis5dQzd3Em0r3ByQMI0CCaGpfJHBVtIUi+l4eyw6CqXBizjMTIw9kcCaBlkCVXcHU5mOyjNW9TP2fGoF6oUaFEldBIgD6J94hhU1X5IVoNIFLY1GREX7Zn1eJVhKofBRsP3eqhYpCRlrHdGp1j2hMmrt+fDkjBbO5O9d/F/02hDzXhnp01To05d8WC+YRsnmMG+wJerY+3OuYqQkWSa32cVE8="
    # ALIAS
    - secure: "OuL6u4LRq2fPalQlmg8ZX+jE4BznfAtfQwxw/B85DXDTFR8AupGpcF1jwMhSBJzRXmkJvZZYgUc3GOqxmudBMxcBQh76MAfZrux7mta1gule29aCGcGeqoNW1d4J43W6F+1Rhh+nMFQX/fnaRaBtLXHOPQYw5/rGix/fcYONy57hwVTRRBkzMFk/7MhgqU5P7YwzJEMfQZTTuYGM1GGW1+kdPaZGkwFP4RN9NPBtcJoqZMdMNpxyDZCwfxTtqWa/OdJEK3DXI5WA6SPXjf3WD7kjuk6WOtUASqrDw/Oi+BudZ88tW25SARcFjMQDR9cWWqIYhENyE4VUEFuP8xi3yjuGq7UVz0UwzciBUfRweIoXpqbIAZsJCzUbFtro2FPuGhIlYpKYUzU26UJqNe1eUOe7NIOZGBNF2L76Bw6GzBQKABLJEUrowgtpaBtRw1z9mNXEgWnUZiBxnSN4pwXnjpYnpS4GO3rL5hwHy4WOyAPw++gCRahPSBpMiDfyjWKaA5YFOYnyzk28ctii9uxwfo57PBi4o+FNxDMgpxQa998luux7spSBoWuTRsF08agZOCp1WscGGabXrAO/1l4+56lZxJVYaZ2z5U//HQJv1SNLn2dD/abMDXCH6whx3kaFsSsIQaZyttmYh+FakXplnurbNWf4YmkQqpDoI6VkwbY="
    # API_KEY
    - secure: "Guf+ItqSTPN9l/yy/pOfbtzpu7G2lBbUZW8ghio/uSUyvbvwB9/tfzV+1TklC+G3x8WgQfD37oEOcxZuBIqTSDw+/7+nwLkMsUh5KjIJwj7Il6EVls+EWKUg7DtNHzduIr6F6tab8/6Gbv2rdKuvksuKZqLQuX6jpzpedXge5s+5RqoBDpNtlnrUmSdBJzIUr12eGvXPcGqEVStYocYszXFAN+7sgiE8C5MvtifYks5M3ZQTX+1HuJq+HcLn1Xbc4zZcZACh22nmFt0dTkmEcc3wYJndSBSv/gbFljMTYZ5hcZXT3Lm2cJI21sZCB+cQ/Cj9TrzhKTZQISNZ4Jx7R1i4udc2105Li8D0/hY6Aix9TNl050AvbmlKGTcLQJLqC+SiSfBmWWMWKs6JsgWePjMEfOVV0zgYfOWK1HeTqcjzLTYaI6JEwmZ/hXP+phDl+QiqmztPbhq4CXbP3Tzq4mF0Mi9vfuxs7HECFxYIniIHVJ09GyVZiSUdOajzBpVBY+euXMQZHWJ81phG/oNpaZSsbsZck2MjoeVt2o6UMV3htpLsRcEuY2Sml9RS9NbGIz9N36MlsepXFLmoaEFtl8w2OH9V/vy5+HWPCpJPAUzk9S1wSlJdeEibycVWSktkIUm/6gB3g5jL3SRblcP+ELpKdiqdJx5U1OBfw9b8YS4="
    # JUHE_API_KEY
    - secure: "oHyoYHAga1k4Q/rcj0cgVpl5tE1yw3dCoVuF1F9l4sNv43ycrXrP8oKE68UFGzseXCEg4lAZaRoz5uVmGUbmKZV3Dv6MO5mQR+i+OaeUxMag4FOUt7bP7iM9F/xqoSG5/ZOVomYHoKhUEE3oQYsnQuNwcpk66VdeMTUaiXgDuVRCCNe5wUrgwsuuGVsMqxIVi+hW8qEKO5wqQyuB/Fwm+dz9jL6XGtopILxyJpiptpQtnkusOxG4JJ3aERw//CavOO62Q2blsQ2wpnyL7tdJnh6LVUmZFDFwFVUytRPC3Yeqmb32umn47srhAXFpFggV9jDdYDDteTjSKw26GvM9PHXNwyPlMtsXXYrpfXcCE1dv9V+HMqkUbHMjSoM/RgnaNUtEBa8JHbJIS2KBKrF06foodIm0TvQO/lc6uKpcx7g65ntHp9WwqM1JcFfFLgiwasRGfQKw7xrPjy8C7F2jYpUJTtaz44mn3TlqI2ITlFgTIp57w3JkdpEFxNg0TlqdBIuH4WbXuFBNy/BfLNikiRlYSqiJGuWq3feFdZlDQT78UJr5nnZQKwT5F9bHzyRW+4qYE+EwOApeGNhewBPpPEBthQaV1atomBzXK9XLywr/bZmxlVMAJOMjBmGS4KfmeIRzmn6GR1A7kHgBgIqCvPjPT3PAGNmXVi1imkyprzo="
    # LEANCLOUD_APP_ID
    - secure: "GLvOiT17vzvUPDfOwLcBAQk9khjQIRssz1meNhRWUZy7A3cUBkuBun8Wh2MtONh23L0LlhZF6weKVzqX0GmRF/yjAXFTw0ulGylz1VFKiGGP0eq6yIJOXVY4AHPqs9LM3Spvx4Wev5u4s/z2OSxGh6LmLMcFFi8wPo414h4WoOIXYtwg+4eaZ3SRXGkGL2mdO3x0QklKGAHGCqyUCEuscPVVXn7CdjtFCODpbeo7SAKpucym4FWpZkplLdpEePaBEQfbXxeCfulf1ADT2PbC1iNziFAIZ/o4lKAoAvX+ZLHlf5Ge9iXSs6I2K7O5hv2nTYZb++gdYOSGby6c2XK4BKUggLBlBeBgEjlAuvWvkZKxwUzTqMqG5n4biwcI5y7dowW/olHQ8iWscOdNneisfecDu+Q2YhvyQPEDNHrmj20Sk6jcLwFqePF/CYGpBoljAJlU1KLouGw0fAWqYCJs6q3AAbaKQO9XYwi8HBOKJ1ZPafiKVkKLjWLuUBYp7a2kJScb6P2jbksWP00D/Nkwo5CmfUDsuM/TaFuA23xfvE3X/3wQse/6nFPjt6AhKEqwOOvzXtUmwktUaycyh1SXkA194sf60eN3n+IG1QhZ58P5kUOvAzPofyIO4PGvs2KMmI/yjwGBJZ2OxCA9XBF4x5KsNp6Ygp+rdxuMwvhmLNw="
    # LEANCLOUD_APP_KEY
    - secure: "ksg39+T1q6ffx4Pvmd6h6XXQD/SAdsd3F25Go8tyr70KBwnVamXAtfAz2j4kjXuzu52YhRXWWwnpgPfKOIAtKGdQE2SxI2UOaNkDS2BL7qQwi8h5Qz7uSW/T01eDxWqcr4uySQ+6AcYtrppQGbIs2rBgc9K6LykVnITMFnzpr98V9IlryHTJ7ZRbQ/4vdIPN+E5S0Vr/Aag5YPZMxg4apGRSn3GGMRM41JbV+Fy6gP65FZTnZtNBKYZuJ2rrnuUROepncMXBBuTYSlZOHYwwSKYQl35Z5KS5vRnLgab/H9J3gjEmVzYxKTpl/YqHqeE6OjG1B4p/kfmpIZFYZGeeRK+yjhOFuxt3NcPy7Xv4WYbcCs3i+sfKCA3BIdTx5vYktws4Ky1XUgqMuvvfxiDezozl7DqIE8b1BHJV6Jq/BDZRDjQKfw69b1UQQZIGbKxv+Nnmk/Bu1P7EQGOAloox3TsBm1XSHySc9aFYacJZVrecAhMInZu8NJa3YsYBOWuNcXGTwty7CRDyQ1TJAXLq4qHX6FoHHPjG7ZLz55YGlcQJgLJvFQLPqvwj6K5vC0RZs23YqmwZRFawtNOThQRyYOSW/XHSugCXS9BXnrOauwzNJFMNbYQv1KRAmQ/qcC2xZvHH3ED2/bz0POUmz+k1tq6pIaUhwEQJG3QWtnNbqHU="
